name: Build & Publish basic-auth-sidecar image to GHCR

on:
  push:
    branches:
      - main
      - 'feature/*'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    env:
      PLATFORMS: linux/arm64,linux/amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        env:
          DESCRIPTION: basic-auth-sidecar is a lightweight authentication sidecar for Envoy proxy.
        with:
          images: ghcr.io/jacero-io/basic-auth-sidecar
          tags: |
            type=semver,pattern=v{{version}},event=tag
            type=semver,pattern=v{{major}}.{{minor}},event=tag
            type=semver,pattern=v{{major}},event=tag
            type=ref,event=pr
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=dev-latest
          labels: |
            org.opencontainers.image.authors=info@jacero.io
            org.opencontainers.image.description=${{ env.DESCRIPTION }}
          annotations: |
            org.opencontainers.image.authors=info@jacero.io
            org.opencontainers.image.description=${{ env.DESCRIPTION }}

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
